eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8222

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**

        - id: school
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**

